### ISSUE TITLE
Store customer profile left navbar placement shifting on switching pages

### ISSUE THREAD

**Issue by shubhamz950** [dailykit/HERN#1088]
**Describe the bug**
On store side, after logging in, in profile section, left column navbar placement changes when we switch between pages such as wallet, referral, etc.

**To Reproduce**
1. Go to store and login
2. Click on profile icon in top navbar
3. Switch between profile pages on left navbar
4. See UI error

**Expected behavior**
Profile Navbar should be fixed on left side as in referral page.

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/84710678/176165642-afbcde0a-99dc-4e54-8e5c-eda739825d22.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/84710678/176165676-ebe8acab-20ac-469d-a955-e585e6cfad16.png">

**Comment by rahul72925** [comment]
Each option in profile section is  a different page. When we click on any section we are redirecting on new page.
