### ISSUE TITLE
Breadcrumb: fixes

### ISSUE THREAD

**Issue by futuregridtechnologies** [dailykit/HERN#156]
Currently we're showing the Ids of the entities example in product or customer

What we need

1. If you'd notice, in the tabs, we are showing the information that is rememberable for the tab. Ideally we should be passing that in breadcrumb instead of id.
2. If the content of breadcrumb is longer, we need to render it neatly. 
![image](https://user-images.githubusercontent.com/49945376/139506031-2d682cfe-0c36-46b7-ac78-4413d7a2ae3d.png)

**Comment by ng11tk** [comment]
@shubhamz950  can you tell how should we processed this

**Comment by shubhamz950** [comment]
@ng11tk we need make navigation breadcrumbs user friendly and easily readable. If any breadcrumb text is long, we should render it neatly.
