### ISSUE TITLE
Clicking on brand (coldPeanuts) gives an error

### ISSUE THREAD

**Issue by chiragsoni81245** [dailykit/HERN#540]
Clicking on brand (coldPeanuts) gives an error

![brand_edit_gives_an_error( coldPeanuts )](https://user-images.githubusercontent.com/52407451/157889941-d058d067-7671-4c17-8dfc-f174902f6b4b.jpeg)
![brand_edit_gives_an_error( coldPeanuts )(error) png](https://user-images.githubusercontent.com/52407451/157889960-b2945fcd-0fde-48ed-8794-4a60433f94bb.jpg)

**Comment by jayant13o6** [comment]
Error Solved.
The value of brandSettings "Script" was an object. we convert it into array of objects.
