### ISSUE TITLE
Create posist's accounting table so kiosk clients integrated with posist can audit the orders

### ISSUE THREAD

**Issue by futuregridtechnologies** [dailykit/HERN#557]
Way to do:

Create a postgres view that contains all the columns needed for this report.

Create a reacttabulator table that contains grouping options by day, kioskId, locationId so report could be grouped.

Allow options to export the report by xlxs, pdf, csv and all as we currently do.

@niku5793 Please help nitin in creating the postgres view for this.

@shubhamz950 please collect the list of columns from rowel 

@deepak-negi-web  help nishu in understanding for identifying posist integrated orders..

On top of my head

cartId, locationId, kioskId, amount, transactionId from the terminal payment, Date, posist customer key (effectively their side of locationId)

**Comment by Rkrahul005** [comment]
Hello Team
please find the columns list
![Columns](https://user-images.githubusercontent.com/91191186/158227431-a6921ee2-9ab3-4f35-bc89-e4a6ac6980e8.PNG)
