### ISSUE TITLE
BreezyChef.com design upgrades

### ISSUE THREAD

**Issue by shubhamz950** [dailykit/HERN#558]
https://www.figma.com/file/3MG5Na9M2NMjvzmMApjvDe/Breezychef?node-id=0%3A1

Breezychef.com needs to be updated to new design (link above).

**Comment by FAsami** [comment]
Planning for this issue, 
https://docs.google.com/document/d/1VPnL34zxtTX6of5kdH5_jaXsO1vGq2G97bhUElPfOzQ/edit?usp=sharing
