### ISSUE TITLE
Kiosk Management Module

### ISSUE THREAD

**Issue by futuregridtechnologies** [dailykit/HERN#561]
Currently, we have supported kiosk management from store side but we lack any admin side interface for it.

Here's the need.

1. List of all the kiosks (kiosk id, order prefix, label, access url, access password)
2. Ability to create a new kiosk
3. Ability to link a kiosk with a single location
4. Ability to link up order tabs that are allowed at a kiosk and setup order prefix
5. Ability to link up posist_tabId at locationKiosk_orderTab table
6. Allow ability to select the printerId available from the list of devices.

@manitrathore Please ask divya or chanchal to design the UI for this before the team starts on this.
@roshandailykit @Rahul199430 Please oversee the design and give your feedback.

Provide instructions on the interfaces kiosk would run on
Provide instruction on what payments are supported for kiosk
Provide instruction on how to setup a kiosk
  Kiosk Mode
  Printer Util
  Posist integration

Allow setting of kiosk config from the kiosk module rather than brand

Allow from a separate interface to turn on the kiosk module and not show it by default so users are not overwhelmed.

@jayant13o6 would take the lead on developing this.
@ng11tk help jayant with the coding side of things as he's fairly new to frontend code writing.
@rahul72925 Give KT of all specifications and database related fields

**Comment by jayant13o6** [comment]
@rahul72925 can you help me how to start this project

**Comment by Deep-mangla** [comment]
Here is design for it
https://www.figma.com/file/DKl2RIVsXcTKqQohNXORGb/?node-id=125%3A293

**Comment by jayant13o6** [comment]
hey @Rahul199430 @rahul72925 @roshandailykit can you please review these designs, and give your feedback

**Comment by Rkrahul005** [comment]
Hello Jayant, Looks fine.

**Comment by jayant13o6** [comment]
@rahul72925 @futuregridtechnologies @ng11tk 
the "basic info" template will be after clicking on "create new kiosk" or clicking existing kiosk??

**Comment by roshandailykit** [comment]
@Deep-mangla Please make the changes as per our discussion on the design.

**Comment by roshandailykit** [comment]
@Deep-mangla Work with @DivyaSingh01 & @chanchal59 to make the gifs on hover for options so that users can understand what each and every option does.

**Comment by Deep-mangla** [comment]
@roshandailykit I've made changes there and I think we should show text with every config as a note instead of hover. It will work for all type of devices.
