### ISSUE TITLE
kiosk payment popup should be config based

### ISSUE THREAD

**Issue by rahul72925** [dailykit/HERN#770]
**Is your feature request related to a problem? Please describe.**
Styling of kiosk's payment popup (in cart page click on `Place Order`) is fixed.
styling -> Popup background color, text color, logo, button style, detail container background color

**Describe the solution you'd like**
Payment popup style should be config based. So this would be easy to manipulate as like other components.

![image](https://user-images.githubusercontent.com/52755891/163106351-fbead7d8-1bba-43c4-a483-838520d45c60.png)

**Comment by futuregridtechnologies** [comment]
@jayant13o6 please coordinate with design team once in regards to what all props to offer in order to achieve maximum flexibility and customisability
