### ISSUE TITLE
OTP is exposed on client side

### ISSUE THREAD

**Issue by FAsami** [dailykit/HERN#774]
Currently, 
- Our OTP is exposed on the client-side as a response. 
![image](https://user-images.githubusercontent.com/43314398/163168340-177972d9-c40e-4786-84d6-2833d201a8ff.png)

Expected behavior, 
- OTP should not be exposed to the client side.

**Comment by futuregridtechnologies** [comment]
@FAsami Can you explain when is this happening? Because with the recent changes that @deepak-negi-web made, we had moved the otp sending mutation at the backend.

**Comment by deepak-negi-web** [comment]
@futuregridtechnologies and @FAsami 
Yes, we have moved our otp sending mutation (sendSms) in the backend
but this otp exposing in client-side is because of the insert mutation that we are firing in otp_transaction table (from client-side) and getting otp(along with id) in the muation result.

**Comment by FAsami** [comment]
I have removed that.
