### ISSUE TITLE
Clone Recipe not working

### ISSUE THREAD

**Issue by futuregridtechnologies** [dailykit/HERN#788]
**Describe the bug**

**To Reproduce**
1. Go to any recipe page
2. Click on clone recipe

it does nothing
**Expected behavior**

Should clone the recipe and should take me to the cloned recipe
check product cloning for the same behavior

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chiragsoni81245** [comment]
@futuregridtechnologies In cloning of recipe, what do we have to do for those ingredients which do not have any processing. like these

![Web capture_6-5-2022_2090_localhost](https://user-images.githubusercontent.com/52407451/167155309-0340faea-eb2f-42aa-9c91-88709ddca3a7.jpeg)

Should we clone them as they are?

**Comment by futuregridtechnologies** [comment]
Yeah, its how it was supposed to be. Isn't it working like that only?
