### ISSUE TITLE
Link brand location to recurrences

### ISSUE THREAD

**Issue by rahul72925** [dailykit/HERN#865]
### Discussed in https://github.com/dailykit/HERN/discussions/834

<div type='discussions-op-text'>

<sup>Originally posted by **rahul72925** April 21, 2022</sup>
**Recurrence**
Admin:
 - configuration of recurrence is available in `Menu App` for each fulfillment type (ONDEMAN_DELIVERY, ONDEMAND_PICKUP, PREORDER_DELIVERY & PREORDER_PICKUP).
 - there is only option for link **Recurrence** with **Brand**.
 - each fulfillment type may have multiple recurrences.
 - each fulfillment type has there own recurrences.
 
Database:
 - `recurrence` table in `fulfillment` schema contain all available recurrences (all type of fulfillment).
 - `brand_recurrence` table in `fulfillment` schema is representing relation of **brand** with **recurrences**. 
 - `brand_recurrence` table has column `brand_location` (relation of **brand** with **location**)
 - if there any `brand_recurrence` available for a particular  **brand_location**  then that `brand_recurrence` will be priority for that particular  **brand_location** other wise **brand** level recurrence will apply.

TO DO:
 - Create  recurrence configuration  **ONEMAND_DINEIN** and **PREORDER_DINEIN** in admin.

**Location**
Admin

 - configuration of **Location** is in `Brand App`.
 - The option to link **Brand** with **Location**  (called brand_location) is available in `Link` tab of location configuration .
 
 Database
 
 - `brand` table in `brands` schema  contain all the brands.
 - `location` table in `brands` schema contain all the location.
 - `brand_location` table in `brand` schema representing relation between  **brand** and **location**.

**Link Recurrence  with brand_location**

 - each **brand_location** may have multiple recurrences.
 - as every fulfillment type has there own recurrences, there would be six tab to select recurrences.
 - each tab contain data of each fulfillment type in table form with **Link** action by which `brand_location` could be **Link** or **Unlink** with `recurrences`.
</div>

**Comment by rahul72925** [comment]
The approach for link brand_location with recurrence may change. @ng11tk  do you think that this flow is more reliable?

**Comment by ng11tk** [comment]
@rahul72925 yes... flow is great, every information which will be requires for this feature is on point

**Comment by rahul72925** [comment]
@ng11tk @shubhamz950 @jayant13o6 
this would be better if we link recurrences with brand location, where we were linking recurrences with brand.
![image](https://user-images.githubusercontent.com/52755891/165677416-6a350e1e-99f4-4874-bb89-79fcb0c5141e.png)

currently we have option to link recurrence with brand. 
Now we will provide one more field `Link With Location`. When click on it, it will open new tunnel `Link Recurrence With Brand location ` where it show all the available location for this brand (basically brand location). And here we can direct link recurrence to `brand_location`.

To get location in tunnel make sure that location is link with that brand.

**Comment by rahul72925** [comment]
**Link recurrence with brand**
Linking recurrence with brand will create a row in `brand_recurrence` table.
|id|brandId|recurrenceId|isActive|brandLocationId|
|--|--|--|--|--|
|1000| 1 |1000  |true|null

**Link recurrence with brand location**
Linking recurrence with brand location will create a row in `brand_recurrence`  table.
|	id|brandId	|recurrenceId|isActive|brandLocationId
|--|--|--|--|--|
|1000| 1 |1000  |true|null
|1001| null |1000  |true|1001

here we know that what is the brandId for recurrence by there brandLocationId so we need not to set brandId again for this entry.

> `id` is primary key of table.
> The pair of `brandId` : `recurrenceId` and `brandLocationId` : `recurrenctId` would be unique.

@jayant13o6 @futuregridtechnologies @shubhamz950

**Comment by jayant13o6** [comment]
> **Link recurrence with brand** Linking recurrence with brand will create a row in `brand_recurrence` table.
> 
> id	brandId	recurrenceId	isActive	brandLocationId
> 1000	1	1000	true	null
> **Link recurrence with brand location** Linking recurrence with brand location will create a row in `brand_recurrence` table.
> 
> id	brandId	recurrenceId	isActive	brandLocationId
> 1000	1	1000	true	null
> 1001	null	1000	true	1001
> here we know that what is the brandId for recurrence by there brandLocationId so we need not to set brandId again for this entry.
> 
> > `id` is primary key of table.
> > The pair of `brandId` : `recurrenceId` and `brandLocationId` : `recurrenctId` would be unique.
> 
> @jayant13o6 @futuregridtechnologies @shubhamz950

Why are we creating new rows instead of updating the previous one? then the pair of `brandId`:`brandLocationId`:`recurrenceId`  will be unique.

**Comment by rahul72925** [comment]
There is 5 location of a brand XYZ (`id=1`).
And we want to run all the location with the same recurrence. 
|id|brandId|recurrenceId|isActive|brandLocationId|
|--|--|--|--|--|
|1000| 1 |1000  |true|null

then this row will applicable for all the brandLocation.

Now we want that there is particular brand location where recurrence would be different (like different time slot for that location). But rest location should have same as last time.

|	id|brandId	|recurrenceId|isActive|brandLocationId
|--|--|--|--|--|
|1001| null |1001  |true|1001

when we doing like this than `brand_location=1001` has `recurrence=1001` not `recurrence=1000` but rest of the locations will run on `recurrence=1000`

@jayant13o6

**Comment by jayant13o6** [comment]
so does that means when brandLocationId is null and but brandId = 1 and recurrenceId =1000,  then all the locations of brandId =1 will have same recurrence? @rahul72925

**Comment by rahul72925** [comment]
except that `brandLocationId=1001` all the location which has `brandId=1` has same recurrence.
