### ISSUE TITLE
Section tabs

### ISSUE THREAD

**Issue by Deep-mangla** [dailykit/HERN#875]
**Description**
Our section tabs are disturbed. Need to fix them

**To Reproduce**
1. Go to Menu app from sidebar
2. Click on Pre-order Delivery
3. See recurrence tabs 

**Expected behavior**
Right now if we add more than 5 days than content is moving out from the tab. We can make the tabs content flexible and also need to decrease their size so that we can get more space for other things. 

**Screenshots**
This is what we've right now
![image](https://user-images.githubusercontent.com/77046184/165728474-b64b15a5-455c-426c-a692-a2da306ec055.png)
This is what we can do
![image](https://user-images.githubusercontent.com/77046184/165728573-94a2af5b-dcfd-463e-bdd0-ee8ef2ba8573.png)

**Comment by shubhamz950** [comment]
@jayant13o6 
https://www.figma.com/file/YSMmAQXBUwJnRAHnwjUTYA/?node-id=0%3A1
