### ISSUE TITLE
Store login : can login/signup when already logged in

### ISSUE THREAD

**Issue by shubhamz950** [dailykit/HERN#881]
**Describe the bug**
A person can login or signup on store even when the person is already logged in to the store. Older login will be replaced by the new login.

**To Reproduce**
1. Go to store login and login with your credentials
2. Visit /login page with url
3. login with any new or same credentials
4. New login will replace the older lgin

**Expected behavior**
When a logged in person visit /login or /signup pages, then he should be redirected back to HOME page.

**Screenshots**
<img width="1440" alt="Screenshot 2022-04-29 at 12 09 37" src="https://user-images.githubusercontent.com/84710678/165895944-7237f190-48be-4258-8356-c6febf02ff70.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by rahul72925** [comment]
Should we show any kind of redirecting message?
