### ISSUE TITLE
Hasura Migrations -- to fix the calculations for billing

### ISSUE THREAD

**Issue by chiragsoni81245** [dailykit/HERN#895]
# Additions

## DB level changes

 - [x] Functions
     - `cartFunctions`.`cartOwnerBilling`
         - Removed `loyaltyPointsUsable:= coalesce((SELECT "order"."loyaltyPointsUsable"(cart)),0);` as its not used anywhere in this function
         - Added `totalToPay := round(totalToPay, 2) - coalesce(walletAmountUsed,0) - coalesce(loyaltyAmountApplied,0);`
         - Modify `balanceToPay := totalToPay  - cart."amount";`
     - `order`.`walletAmountUsable`
         - Instead of taking totalPrice from totalPrice function, now it's coming from `balanceToPay` field of  `cartFunctions`.`cartOwnerBilling` function
     - `order`.`loyaltyPointsUsable`
         -  Instead of taking totalPrice from totalPrice function, now it's coming from `balanceToPay` field of  `cartFunctions`.`cartOwnerBilling` function
         - Make pointsUsable from `ROUND(amount/rate);` to `FLOOR(amount/rate);` as when we have an amount in float value then the ROUND function can give us the next integer. 
             - Example: for `ROUND(45.6/1)` it will give us `46` but that is not acceptable as a user should be able to use only 45 points for rate 1
     - `crm."setWalletAmountUsedInCart"`
         - Whenever the `balanceToPay` will be negative then walletAmountUsed will be set to zero 
     - `crm."setLoyaltyPointsUsedInCart"`
         - Whenever the `balanceToPay` will be negative then loyaltyPointsUsed will be set to zero

**Comment by rahul72925** [comment]
we are using `billingDetails` to show information in `CartDetails` component. Are we changing it to `cartOwnerBilling`?

**Comment by chiragsoni81245** [comment]
@rahul72925 Yes are changing it to cartOwnerBillingDetails
