### ISSUE TITLE
Kiosk: When all product option is unpublished or unavailable, that product gives reload error 

### ISSUE THREAD

**Issue by shubhamz950** [dailykit/HERN#936]
when all product option is unpublished or unavailable from operation mode brand location manager, opening that product gives reload error

<img width="1440" alt="Screenshot 2022-05-12 at 23 59 21" src="https://user-images.githubusercontent.com/84710678/168150194-1e448d85-ddc1-4b0d-9fbf-8a748e547ed0.png">

**Comment by rahul72925** [comment]
That means the modifier popup would not open if there is no published or available product option. @shubhamz950
