### ISSUE TITLE
Store: Breezychef's referral and loyalty point page is not working

### ISSUE THREAD

**Issue by shubhamz950** [dailykit/HERN#940]
**Describe the bug**
Store: Breezychef's referral and loyalty point page is not working, pages are published from admin, and both are activated from brand settings as well. Also, there are multiple brandsetting for loyalty and referral setting.

**To Reproduce**
1. Go to store
2. Login and click on profile
3. go to referral or loyalty points

**Expected behavior**
Referral page or. loyalty points pages should open.

**Screenshots**
<img width="1440" alt="Screenshot 2022-05-13 at 12 55 34" src="https://user-images.githubusercontent.com/84710678/168232855-9d6d57b6-1e76-4207-afa9-c32e41f405b3.png">
<img width="1440" alt="image (1)" src="https://user-images.githubusercontent.com/84710678/168233097-ce1fed61-62aa-4a52-af7d-ce40b04e54f7.png">

**Comment by chiragsoni81245** [comment]
@shubhamz950 This issue is resolved. the cause for this was, breezychef has some extra brandSetting entry for loyalty points and referrals. now, these entries are removed.
