### ISSUE TITLE
Product Options: when default product option made available or unavailable, in both case "switch off" prompt shows

### ISSUE THREAD

**Issue by shubhamz950** [dailykit/HERN#948]
**Describe the bug**
In products -> for any product options, if a default product option is made unavailable or unpublished, it shows a prompt to confirm it, but when it's made published or available same prompt shows.

**To Reproduce**
1. Go to 'Admin product app
2. Click on any product and open it's product options
3. Scroll down to options, open them and toggle default product option's availability/published toggle
4. See prompt

**Expected behavior**
Prompt should show only when toggles are made off for default option not when they are turned on.

**Screenshots**
<img width="1440" alt="Screenshot 2022-05-13 at 19 35 40" src="https://user-images.githubusercontent.com/84710678/168519943-4750656d-8f21-40f2-bf56-894d933c857e.png">

**Comment by jayant13o6** [comment]
The Default option should remain off for a product option until it is Published and Available both

**Comment by shubhamz950** [comment]
Yes, when a product option is unavailable or unpublished, then "make default" option should be disabled
