### ISSUE TITLE
Not able to Set Kiosk Timings

### ISSUE THREAD

**Issue by Rkrahul005** [dailykit/HERN#962]
When we click on recurrences to set the kiosk timings we are getting blank.
Nothing happening.
Please check the attached image
![image](https://user-images.githubusercontent.com/91191186/169223856-4aab4134-6fc4-4975-8cd7-4ec093433b45.png)

**Comment by shubhamz950** [comment]
@Rkrahul005 Check if it's working now.

**Comment by jayant13o6** [comment]
Issue Resolved:
Herfy's database updated:
"fullfilment" schema > brand_recurrence table
ID column created and set as primary key.
(Databases of other instances have been updated as well)
