### ISSUE TITLE
Store Not Available during checkout

### ISSUE THREAD

**Issue by Rkrahul005** [dailykit/HERN#963]
In Breezychef, when we select an item and address to place an order. After the selection of addresses, it's showing No store available.
Please check the screenshot
![WhatsApp Image 2022-05-19 at 9 50 04 AM](https://user-images.githubusercontent.com/91191186/169224380-87bede7f-2cad-440b-a8b3-1ef9de5e051a.jpeg)

**Comment by shubhamz950** [comment]
Someone changed the store's location in DB from Pune to Bangalore. It's fixed now.
