### ISSUE TITLE
Fix: Pre-order and OnDemand dine fulfillment

### ISSUE THREAD

**Issue by jayant13o6** [dailykit/HERN#984]
**Is your feature request related to a problem? Please describe.**
Need to add leadTime and PrepTime in PreOrder and OnDemand dine-in fulfillment like in pick-up
![image](https://user-images.githubusercontent.com/89663357/170415999-5fdff5bd-4ec3-49d1-b2e4-d99a04723a1e.png)

**Comment by jayant13o6** [comment]
@rahul72925 Do we need to add anything else in this?

**Comment by rahul72925** [comment]
this is in dinein? @jayant13o6

**Comment by jayant13o6** [comment]
> this is in dinein? @jayant13o6

yes this is for dine-in
